# Generated by Django 5.0.7 on 2024-07-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(auto_now_add=True),
        ),
    ]
