# Generated by Django 5.0.7 on 2024-07-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0002_rename_amount_payment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5),
        ),
    ]
