# Generated by Django 5.0.7 on 2024-07-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0005_customer_location_alter_customer_id_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='balance',
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=22.5, max_digits=5),
        ),
    ]
